"""empty message

Revision ID: 0aa8e0442999
Revises: b0a4c1638901
Create Date: 2021-12-27 21:30:05.984450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa8e0442999'
down_revision = 'b0a4c1638901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('advertisements_company_user_id_fkey', 'advertisements', type_='foreignkey')
    op.create_foreign_key(None, 'advertisements', 'company_users', ['company_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.create_foreign_key('advertisements_company_user_id_fkey', 'advertisements', 'company_users', ['company_user_id'], ['id'])
    # ### end Alembic commands ###
