"""empty message

Revision ID: 3e30730cc551
Revises: ba30eeb01725
Create Date: 2021-12-26 18:01:48.575219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e30730cc551'
down_revision = 'ba30eeb01725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('advertisements_company_user_id_fkey', 'advertisements', type_='foreignkey')
    op.create_foreign_key(None, 'advertisements', 'company_users', ['company_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.create_foreign_key('advertisements_company_user_id_fkey', 'advertisements', 'company_users', ['company_user_id'], ['id'])
    # ### end Alembic commands ###
