"""empty message

Revision ID: 5f00dab9d233
Revises: d1bbdf46eb92
Create Date: 2021-12-20 13:14:48.634890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f00dab9d233'
down_revision = 'd1bbdf46eb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'position')
    op.drop_column('applicant_users', 'previous_position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant_users', sa.Column('previous_position', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('advertisements', sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
