"""empty message

Revision ID: 9241a3321420
Revises: 6c6cfadb4bde
Create Date: 2021-12-20 00:18:39.322978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9241a3321420'
down_revision = '6c6cfadb4bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills_users',
    sa.Column('applicant_user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['applicant_users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('applicant_user_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills_users')
    # ### end Alembic commands ###
