"""empty message

Revision ID: aeb27ca3619c
Revises: 9241a3321420
Create Date: 2021-12-20 00:24:24.419664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb27ca3619c'
down_revision = '9241a3321420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_skills',
    sa.Column('applicant_user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['applicant_users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('applicant_user_id', 'skill_id')
    )
    op.drop_table('skills_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills_users',
    sa.Column('applicant_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['applicant_users.id'], name='skills_users_applicant_user_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='skills_users_skill_id_fkey'),
    sa.PrimaryKeyConstraint('applicant_user_id', 'skill_id', name='skills_users_pkey')
    )
    op.drop_table('users_skills')
    # ### end Alembic commands ###
