"""empty message

Revision ID: ba30eeb01725
Revises: 5f00dab9d233
Create Date: 2021-12-20 14:13:20.924044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba30eeb01725'
down_revision = '5f00dab9d233'
branch_labels = None
depends_on = None


def upgrade():
    positions = sa.Enum('software_developer', 'hr', 'manager', 'qa', 'marketing_expert', 'analyst',
                        'system_administrator', 'devops', 'unemployed', 'unknown', name='positions')
    positions.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('position', sa.Enum('software_developer', 'hr', 'manager', 'qa', 'marketing_expert', 'analyst', 'system_administrator', 'devops', 'unemployed', 'unknown', name='positions'), nullable=True))
    op.add_column('applicant_users', sa.Column('position', sa.Enum('software_developer', 'hr', 'manager', 'qa', 'marketing_expert', 'analyst', 'system_administrator', 'devops', 'unemployed', 'unknown', name='positions'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicant_users', 'position')
    op.drop_column('advertisements', 'position')
    # ### end Alembic commands ###
