"""empty message

Revision ID: df0725f90ba2
Revises: 547a68bccc62
Create Date: 2021-12-20 09:53:43.731679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0725f90ba2'
down_revision = '547a68bccc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisements_skills')
    op.drop_table('users_skills')
    op.add_column('applied_advertisements', sa.Column('advertisement_id', sa.Integer(), nullable=False))
    op.drop_constraint('applied_advertisements_skill_id_fkey', 'applied_advertisements', type_='foreignkey')
    op.create_foreign_key(None, 'applied_advertisements', 'advertisements', ['advertisement_id'], ['id'])
    op.drop_column('applied_advertisements', 'skill_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applied_advertisements', sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'applied_advertisements', type_='foreignkey')
    op.create_foreign_key('applied_advertisements_skill_id_fkey', 'applied_advertisements', 'advertisements', ['skill_id'], ['id'])
    op.drop_column('applied_advertisements', 'advertisement_id')
    op.create_table('users_skills',
    sa.Column('applicant_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['applicant_users.id'], name='users_skills_applicant_user_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='users_skills_skill_id_fkey'),
    sa.PrimaryKeyConstraint('applicant_user_id', 'skill_id', name='users_skills_pkey')
    )
    op.create_table('advertisements_skills',
    sa.Column('advertisement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], name='advertisements_skills_advertisement_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='advertisements_skills_skill_id_fkey'),
    sa.PrimaryKeyConstraint('advertisement_id', 'skill_id', name='advertisements_skills_pkey')
    )
    # ### end Alembic commands ###
